name: Deploy Firebase Functions

on:
  push:
    branches:
      - main  # change if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Step 4: Deploy Functions using service account
      - name: Deploy Firebase Functions
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
        run: |
          # Convert escaped \n into real newlines for private key
          mkdir -p ~/.firebase
          echo "${FIREBASE_PRIVATE_KEY}" | sed 's/\\n/\n/g' > ~/.firebase/service-account.json

          # Authenticate Firebase CLI using the service account JSON
          firebase deploy --only functions --project $FIREBASE_PROJECT_ID --token "$(cat ~/.firebase/service-account.json)"
